# Generated by Django 5.2 on 2025-04-24 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('visit_date', models.DateField(verbose_name='行った日')),
                ('visit_name', models.CharField(max_length=100, verbose_name='行った店')),
                ('visit_company', models.TextField(blank=True, verbose_name='行った人')),
                ('visit_cost', models.IntegerField(verbose_name='かかった金額')),
                ('visit_picture1', models.ImageField(blank=True, null=True, upload_to='tbtlog/picture/', verbose_name='行った写真1')),
                ('visit_picture2', models.ImageField(blank=True, null=True, upload_to='tbtlog/picture/', verbose_name='行った写真2')),
                ('visit_picture3', models.ImageField(blank=True, null=True, upload_to='tbtlog/picture/', verbose_name='行った写真3')),
                ('visit_picture4', models.ImageField(blank=True, null=True, upload_to='tbtlog/picture/', verbose_name='行った写真4')),
                ('visit_picture5', models.ImageField(blank=True, null=True, upload_to='tbtlog/picture/', verbose_name='行った写真5')),
                ('note', models.TextField(blank=True, max_length=300, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
